### ISSUE TITLE
Dm4 spectrum doesn't load properly

### ISSUE THREAD

**Issue by PauTorru** [joverbee/pyEELSMODEL#22]
Loads negative offset value when it is not:
<img width="293" alt="Screenshot 2024-04-18 090408" src="https://github.com/joverbee/pyEELSMODEL/assets/17293096/c480d25a-dd4d-4248-a8a3-d717cc4763ac">

**Comment by daenjannis** [comment]
This is indeed a problem in the load function which needs to be resolved. 
The current solution is adding the flip_sign=True argument to the load function as following.
```python
nno = em.Spectrum.load("nno.dm4", flip_sign=True)
```

**Comment by joverbee** [comment]
Can this issue be closed?

**Comment by PauTorru** [comment]
Yes on my side!
