### ISSUE TITLE
tqdm  progress bars

### ISSUE THREAD

**Issue by PauTorru** [joverbee/pyEELSMODEL#30]
Hi,

I noticed that in some instances (e.g. multi_fit), the tqdm progress bar only shows iters/s but not how much is left of the process.
Aparently, it is because np.ndindex doesn't show its total length. It could be set by setting the total manually:

`for index in tqdm(np.ndindex(shape),total=np.prod(shape),leave=True,position=0):`

It is a cosmetic issue, but could this be adressed?

**Comment by arnoannys** [comment]
Hi Pau, Thanks, that's a good suggestion. added it
